apiVersion: v1
kind: Service
metadata:
  name: wa-ordertoolsapi-service
spec:
  selector:
    app: wa-ordertoolsapi
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer